// <auto-generated />
using System;
using ApiVentas.ApiRest.Services.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiVentas.ApiRest.Migrations
{
    [DbContext(typeof(VentasContext))]
    [Migration("20210306073541_carga")]
    partial class carga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Articulo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("IdArticulo");

                    b.ToTable("Product", "DBO");

                    b.HasData(
                        new
                        {
                            IdArticulo = 1,
                            Nombre = "Articulo 1",
                            Precio = 101
                        },
                        new
                        {
                            IdArticulo = 2,
                            Nombre = "Articulo 2",
                            Precio = 102
                        },
                        new
                        {
                            IdArticulo = 3,
                            Nombre = "Articulo 3",
                            Precio = 103
                        },
                        new
                        {
                            IdArticulo = 4,
                            Nombre = "Articulo 4",
                            Precio = 104
                        },
                        new
                        {
                            IdArticulo = 5,
                            Nombre = "Articulo 5",
                            Precio = 105
                        },
                        new
                        {
                            IdArticulo = 6,
                            Nombre = "Articulo 6",
                            Precio = 106
                        },
                        new
                        {
                            IdArticulo = 7,
                            Nombre = "Articulo 7",
                            Precio = 107
                        },
                        new
                        {
                            IdArticulo = 8,
                            Nombre = "Articulo 8",
                            Precio = 108
                        },
                        new
                        {
                            IdArticulo = 9,
                            Nombre = "Articulo 9",
                            Precio = 109
                        },
                        new
                        {
                            IdArticulo = 10,
                            Nombre = "Articulo 10",
                            Precio = 110
                        },
                        new
                        {
                            IdArticulo = 11,
                            Nombre = "Articulo 11",
                            Precio = 111
                        },
                        new
                        {
                            IdArticulo = 12,
                            Nombre = "Articulo 12",
                            Precio = 112
                        },
                        new
                        {
                            IdArticulo = 13,
                            Nombre = "Articulo 13",
                            Precio = 113
                        },
                        new
                        {
                            IdArticulo = 14,
                            Nombre = "Articulo 14",
                            Precio = 114
                        },
                        new
                        {
                            IdArticulo = 15,
                            Nombre = "Articulo 15",
                            Precio = 115
                        },
                        new
                        {
                            IdArticulo = 16,
                            Nombre = "Articulo 16",
                            Precio = 116
                        },
                        new
                        {
                            IdArticulo = 17,
                            Nombre = "Articulo 17",
                            Precio = 117
                        },
                        new
                        {
                            IdArticulo = 18,
                            Nombre = "Articulo 18",
                            Precio = 118
                        },
                        new
                        {
                            IdArticulo = 19,
                            Nombre = "Articulo 19",
                            Precio = 119
                        },
                        new
                        {
                            IdArticulo = 20,
                            Nombre = "Articulo 20",
                            Precio = 120
                        },
                        new
                        {
                            IdArticulo = 21,
                            Nombre = "Articulo 21",
                            Precio = 121
                        },
                        new
                        {
                            IdArticulo = 22,
                            Nombre = "Articulo 22",
                            Precio = 122
                        },
                        new
                        {
                            IdArticulo = 23,
                            Nombre = "Articulo 23",
                            Precio = 123
                        },
                        new
                        {
                            IdArticulo = 24,
                            Nombre = "Articulo 24",
                            Precio = 124
                        },
                        new
                        {
                            IdArticulo = 25,
                            Nombre = "Articulo 25",
                            Precio = 125
                        },
                        new
                        {
                            IdArticulo = 26,
                            Nombre = "Articulo 26",
                            Precio = 126
                        },
                        new
                        {
                            IdArticulo = 27,
                            Nombre = "Articulo 27",
                            Precio = 127
                        },
                        new
                        {
                            IdArticulo = 28,
                            Nombre = "Articulo 28",
                            Precio = 128
                        },
                        new
                        {
                            IdArticulo = 29,
                            Nombre = "Articulo 29",
                            Precio = 129
                        },
                        new
                        {
                            IdArticulo = 30,
                            Nombre = "Articulo 30",
                            Precio = 130
                        },
                        new
                        {
                            IdArticulo = 31,
                            Nombre = "Articulo 31",
                            Precio = 131
                        },
                        new
                        {
                            IdArticulo = 32,
                            Nombre = "Articulo 32",
                            Precio = 132
                        },
                        new
                        {
                            IdArticulo = 33,
                            Nombre = "Articulo 33",
                            Precio = 133
                        },
                        new
                        {
                            IdArticulo = 34,
                            Nombre = "Articulo 34",
                            Precio = 134
                        },
                        new
                        {
                            IdArticulo = 35,
                            Nombre = "Articulo 35",
                            Precio = 135
                        },
                        new
                        {
                            IdArticulo = 36,
                            Nombre = "Articulo 36",
                            Precio = 136
                        },
                        new
                        {
                            IdArticulo = 37,
                            Nombre = "Articulo 37",
                            Precio = 137
                        },
                        new
                        {
                            IdArticulo = 38,
                            Nombre = "Articulo 38",
                            Precio = 138
                        },
                        new
                        {
                            IdArticulo = 39,
                            Nombre = "Articulo 39",
                            Precio = 139
                        },
                        new
                        {
                            IdArticulo = 40,
                            Nombre = "Articulo 40",
                            Precio = 140
                        },
                        new
                        {
                            IdArticulo = 41,
                            Nombre = "Articulo 41",
                            Precio = 141
                        },
                        new
                        {
                            IdArticulo = 42,
                            Nombre = "Articulo 42",
                            Precio = 142
                        },
                        new
                        {
                            IdArticulo = 43,
                            Nombre = "Articulo 43",
                            Precio = 143
                        },
                        new
                        {
                            IdArticulo = 44,
                            Nombre = "Articulo 44",
                            Precio = 144
                        },
                        new
                        {
                            IdArticulo = 45,
                            Nombre = "Articulo 45",
                            Precio = 145
                        },
                        new
                        {
                            IdArticulo = 46,
                            Nombre = "Articulo 46",
                            Precio = 146
                        },
                        new
                        {
                            IdArticulo = 47,
                            Nombre = "Articulo 47",
                            Precio = 147
                        },
                        new
                        {
                            IdArticulo = 48,
                            Nombre = "Articulo 48",
                            Precio = 148
                        },
                        new
                        {
                            IdArticulo = 49,
                            Nombre = "Articulo 49",
                            Precio = 149
                        },
                        new
                        {
                            IdArticulo = 50,
                            Nombre = "Articulo 50",
                            Precio = 150
                        },
                        new
                        {
                            IdArticulo = 51,
                            Nombre = "Articulo 51",
                            Precio = 151
                        },
                        new
                        {
                            IdArticulo = 52,
                            Nombre = "Articulo 52",
                            Precio = 152
                        },
                        new
                        {
                            IdArticulo = 53,
                            Nombre = "Articulo 53",
                            Precio = 153
                        },
                        new
                        {
                            IdArticulo = 54,
                            Nombre = "Articulo 54",
                            Precio = 154
                        },
                        new
                        {
                            IdArticulo = 55,
                            Nombre = "Articulo 55",
                            Precio = 155
                        },
                        new
                        {
                            IdArticulo = 56,
                            Nombre = "Articulo 56",
                            Precio = 156
                        },
                        new
                        {
                            IdArticulo = 57,
                            Nombre = "Articulo 57",
                            Precio = 157
                        },
                        new
                        {
                            IdArticulo = 58,
                            Nombre = "Articulo 58",
                            Precio = 158
                        },
                        new
                        {
                            IdArticulo = 59,
                            Nombre = "Articulo 59",
                            Precio = 159
                        },
                        new
                        {
                            IdArticulo = 60,
                            Nombre = "Articulo 60",
                            Precio = 160
                        },
                        new
                        {
                            IdArticulo = 61,
                            Nombre = "Articulo 61",
                            Precio = 161
                        },
                        new
                        {
                            IdArticulo = 62,
                            Nombre = "Articulo 62",
                            Precio = 162
                        },
                        new
                        {
                            IdArticulo = 63,
                            Nombre = "Articulo 63",
                            Precio = 163
                        },
                        new
                        {
                            IdArticulo = 64,
                            Nombre = "Articulo 64",
                            Precio = 164
                        },
                        new
                        {
                            IdArticulo = 65,
                            Nombre = "Articulo 65",
                            Precio = 165
                        },
                        new
                        {
                            IdArticulo = 66,
                            Nombre = "Articulo 66",
                            Precio = 166
                        },
                        new
                        {
                            IdArticulo = 67,
                            Nombre = "Articulo 67",
                            Precio = 167
                        },
                        new
                        {
                            IdArticulo = 68,
                            Nombre = "Articulo 68",
                            Precio = 168
                        },
                        new
                        {
                            IdArticulo = 69,
                            Nombre = "Articulo 69",
                            Precio = 169
                        },
                        new
                        {
                            IdArticulo = 70,
                            Nombre = "Articulo 70",
                            Precio = 170
                        },
                        new
                        {
                            IdArticulo = 71,
                            Nombre = "Articulo 71",
                            Precio = 171
                        },
                        new
                        {
                            IdArticulo = 72,
                            Nombre = "Articulo 72",
                            Precio = 172
                        },
                        new
                        {
                            IdArticulo = 73,
                            Nombre = "Articulo 73",
                            Precio = 173
                        },
                        new
                        {
                            IdArticulo = 74,
                            Nombre = "Articulo 74",
                            Precio = 174
                        },
                        new
                        {
                            IdArticulo = 75,
                            Nombre = "Articulo 75",
                            Precio = 175
                        },
                        new
                        {
                            IdArticulo = 76,
                            Nombre = "Articulo 76",
                            Precio = 176
                        },
                        new
                        {
                            IdArticulo = 77,
                            Nombre = "Articulo 77",
                            Precio = 177
                        },
                        new
                        {
                            IdArticulo = 78,
                            Nombre = "Articulo 78",
                            Precio = 178
                        },
                        new
                        {
                            IdArticulo = 79,
                            Nombre = "Articulo 79",
                            Precio = 179
                        },
                        new
                        {
                            IdArticulo = 80,
                            Nombre = "Articulo 80",
                            Precio = 180
                        },
                        new
                        {
                            IdArticulo = 81,
                            Nombre = "Articulo 81",
                            Precio = 181
                        },
                        new
                        {
                            IdArticulo = 82,
                            Nombre = "Articulo 82",
                            Precio = 182
                        },
                        new
                        {
                            IdArticulo = 83,
                            Nombre = "Articulo 83",
                            Precio = 183
                        },
                        new
                        {
                            IdArticulo = 84,
                            Nombre = "Articulo 84",
                            Precio = 184
                        },
                        new
                        {
                            IdArticulo = 85,
                            Nombre = "Articulo 85",
                            Precio = 185
                        },
                        new
                        {
                            IdArticulo = 86,
                            Nombre = "Articulo 86",
                            Precio = 186
                        },
                        new
                        {
                            IdArticulo = 87,
                            Nombre = "Articulo 87",
                            Precio = 187
                        },
                        new
                        {
                            IdArticulo = 88,
                            Nombre = "Articulo 88",
                            Precio = 188
                        },
                        new
                        {
                            IdArticulo = 89,
                            Nombre = "Articulo 89",
                            Precio = 189
                        },
                        new
                        {
                            IdArticulo = 90,
                            Nombre = "Articulo 90",
                            Precio = 190
                        },
                        new
                        {
                            IdArticulo = 91,
                            Nombre = "Articulo 91",
                            Precio = 191
                        },
                        new
                        {
                            IdArticulo = 92,
                            Nombre = "Articulo 92",
                            Precio = 192
                        },
                        new
                        {
                            IdArticulo = 93,
                            Nombre = "Articulo 93",
                            Precio = 193
                        },
                        new
                        {
                            IdArticulo = 94,
                            Nombre = "Articulo 94",
                            Precio = 194
                        },
                        new
                        {
                            IdArticulo = 95,
                            Nombre = "Articulo 95",
                            Precio = 195
                        },
                        new
                        {
                            IdArticulo = 96,
                            Nombre = "Articulo 96",
                            Precio = 196
                        },
                        new
                        {
                            IdArticulo = 97,
                            Nombre = "Articulo 97",
                            Precio = 197
                        },
                        new
                        {
                            IdArticulo = 98,
                            Nombre = "Articulo 98",
                            Precio = 198
                        },
                        new
                        {
                            IdArticulo = 99,
                            Nombre = "Articulo 99",
                            Precio = 199
                        },
                        new
                        {
                            IdArticulo = 100,
                            Nombre = "Articulo 100",
                            Precio = 200
                        });
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.ArticuloImagen", b =>
                {
                    b.Property<int>("IdArticuloImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGenerado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArticuloImagen");

                    b.HasIndex("IdArticulo");

                    b.ToTable("ProductImage", "DBO");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.ArticuloImagen", b =>
                {
                    b.HasOne("ApiVentas.ApiRest.Services.Entidades.Articulo", "Articulo")
                        .WithMany("ArticuloImagen")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Pedido", b =>
                {
                    b.HasOne("ApiVentas.ApiRest.Services.Entidades.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Articulo", b =>
                {
                    b.Navigation("ArticuloImagen");
                });

            modelBuilder.Entity("ApiVentas.ApiRest.Services.Entidades.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
